# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 739edb8354f30ee6e4f3f1544885fd51a76c15a99c4d98415f6f6f05c2523967993185658ca4f73d0c8a4bea080b95b8ee688c376fc1f4fd5132b20b889230de

test:
  secret_key_base: 3b9aeceb20b43137cf92a06460e38a2b9eae774f209c49309783d96db7947717c3d7e1dbf3844b438c5dd2d710b23f05e91ad60903fcda7131d7a40701e56499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
